import React, { useState } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  ScrollView,
  TextInput,
  Modal,
  Share,
  Platform,
  Alert
} from 'react-native';

export interface CallSheetItem {
  index: number;
  role: string;
  type: string;
  txFreq: number;
  rxFreq?: number;
  split?: string;
  tone: string;
  zoneName: string;
}

interface Props {
  visible: boolean;
  onClose: () => void;
  items: CallSheetItem[];
  onUpdateRole: (index: number, role: string) => void;
  onUpdateTone: (index: number, tone: string) => void;
  activeZoneName?: string;
}

export const CrewCallSheetModal: React.FC<Props> = ({
  visible,
  onClose,
  items,
  onUpdateRole,
  onUpdateTone,
  activeZoneName
}) => {
  const [showName, setShowName] = useState('OB PRODUCTION SHOW');

  // Format as Plain Text Call Sheet
  const generateTextCallSheet = () => {
    let out = `========================================================\n`;
    out += `        CREW RADIO FREQUENCY CALL SHEET\n`;
    out += `        SHOW: ${showName.toUpperCase()}\n`;
    out += `========================================================\n\n`;
    out += `CH | ROLE / ASSIGNMENT   | TYPE   | BASE TX    | PORT TX    | TONE     | ZONE\n`;
    out += `---|---------------------|--------|------------|------------|----------|------\n`;

    items.forEach((it, idx) => {
      const chStr = (idx + 1).toString().padStart(2, '0');
      const roleStr = (it.role || `Radio ${idx + 1}`).padEnd(19, ' ').slice(0, 19);
      const typeStr = it.type.padEnd(6, ' ').slice(0, 6);
      const txStr = it.txFreq ? `${it.txFreq.toFixed(5)}`.padEnd(10, ' ') : '   ---    ';
      const rxStr = it.rxFreq ? `${it.rxFreq.toFixed(5)}`.padEnd(10, ' ') : ' SIMPLEX  ';
      const toneStr = (it.tone || '100.0Hz').padEnd(8, ' ');
      const zoneStr = it.zoneName.slice(0, 10);

      out += `${chStr} | ${roleStr} | ${typeStr} | ${txStr} | ${rxStr} | ${toneStr} | ${zoneStr}\n`;
    });

    out += `\n========================================================\n`;
    out += `Generated by RF Suite Talkback Coordination\n`;
    return out;
  };

  // Format as CSV for radio programming
  const generateCsvCallSheet = () => {
    let csv = `Channel,Role,Type,BaseTxMHz,PortTxMHz,SplitMHz,SubTone,ZoneName\n`;
    items.forEach((it, idx) => {
      const portTx = it.rxFreq ? it.rxFreq.toFixed(5) : '';
      const split = it.split || '';
      csv += `${idx + 1},"${it.role || `Radio ${idx + 1}`}",${it.type},${it.txFreq.toFixed(5)},${portTx},"${split}","${it.tone || '100.0Hz'}","${it.zoneName}"\n`;
    });
    return csv;
  };

  const handleShare = async () => {
    try {
      const text = generateTextCallSheet();
      await Share.share({
        message: text,
        title: `${showName} - Frequency Call Sheet`
      });
    } catch (err) {
      console.warn('Share error', err);
    }
  };

  const handleCopyCsv = async () => {
    const csv = generateCsvCallSheet();
    try {
      await Share.share({
        message: csv,
        title: `${showName} CSV Data`
      });
    } catch (err) {
      console.warn('CSV share error', err);
    }
  };

  return (
    <Modal animationType="slide" transparent={true} visible={visible} onRequestClose={onClose}>
      <View style={styles.modalBackdrop}>
        <View style={styles.modalCard}>
          {/* Header */}
          <View style={styles.headerRow}>
            <View>
              <Text style={styles.modalTitle}>CREW FREQUENCY CALL SHEET</Text>
              <Text style={styles.modalSub}>COMMUNICATIONS DISTRIBUTION MATRIX</Text>
            </View>
            <TouchableOpacity style={styles.closeBtn} onPress={onClose}>
              <Text style={styles.closeBtnText}>✕</Text>
            </TouchableOpacity>
          </View>

          {/* Show Title Input */}
          <View style={styles.showNameRow}>
            <Text style={styles.showLabel}>SHOW TITLE:</Text>
            <TextInput
              style={styles.showInput}
              value={showName}
              onChangeText={setShowName}
              placeholder="Show Name / OB Unit..."
              placeholderTextColor="#475569"
            />
          </View>

          {/* Export Action Buttons */}
          <View style={styles.actionRow}>
            <TouchableOpacity
              activeOpacity={0.8}
              style={[styles.actionBtn, { backgroundColor: '#0284c7', borderColor: '#38bdf8' }]}
              onPress={handleShare}
            >
              <Text style={styles.actionBtnText}>📤 SHARE CALL SHEET</Text>
            </TouchableOpacity>

            <TouchableOpacity
              activeOpacity={0.8}
              style={[styles.actionBtn, { backgroundColor: '#0f766e', borderColor: '#2dd4bf' }]}
              onPress={handleCopyCsv}
            >
              <Text style={styles.actionBtnText}>📄 EXPORT RADIO CSV</Text>
            </TouchableOpacity>
          </View>

          {/* Table Header */}
          <View style={styles.tableHeaderRow}>
            <Text style={[styles.th, { width: 30 }]}>CH</Text>
            <Text style={[styles.th, { flex: 1.5 }]}>ROLE / USER</Text>
            <Text style={[styles.th, { width: 45 }]}>TYPE</Text>
            <Text style={[styles.th, { flex: 1.2, textAlign: 'center' }]}>BASE TX</Text>
            <Text style={[styles.th, { flex: 1.2, textAlign: 'center' }]}>PORT TX</Text>
            <Text style={[styles.th, { width: 55, textAlign: 'center' }]}>TONE</Text>
          </View>

          {/* Table Rows */}
          <ScrollView style={styles.tableScroll} nestedScrollEnabled={true}>
            {items.length === 0 ? (
              <Text style={styles.emptyText}>
                No coordinated channels found. Co-ordinate zones first.
              </Text>
            ) : (
              items.map((it, idx) => {
                const isDup = it.type === 'DUP';
                return (
                  <View key={`sheet_${idx}`} style={styles.tableRow}>
                    <Text style={styles.chNum}>{(idx + 1).toString().padStart(2, '0')}</Text>

                    {/* Role Input */}
                    <TextInput
                      style={styles.roleInput}
                      value={it.role}
                      placeholder={`Radio ${idx + 1}`}
                      placeholderTextColor="#475569"
                      onChangeText={(v) => onUpdateRole(idx, v)}
                    />

                    {/* Type Badge */}
                    <View
                      style={[
                        styles.typePill,
                        isDup ? styles.typePillDup : styles.typePillSimp
                      ]}
                    >
                      <Text style={styles.typePillText}>{it.type}</Text>
                    </View>

                    {/* Base TX */}
                    <Text style={styles.freqCell}>{it.txFreq ? it.txFreq.toFixed(5) : '---'}</Text>

                    {/* Port TX */}
                    <Text style={[styles.freqCell, !isDup && { color: '#64748b' }]}>
                      {isDup && it.rxFreq ? it.rxFreq.toFixed(5) : 'SIMPLEX'}
                    </Text>

                    {/* Tone Input */}
                    <TextInput
                      style={styles.toneInput}
                      value={it.tone || '100.0'}
                      onChangeText={(v) => onUpdateTone(idx, v)}
                    />
                  </View>
                );
              })
            )}
          </ScrollView>

          {/* Bottom dismissal */}
          <TouchableOpacity style={styles.doneBtn} onPress={onClose}>
            <Text style={styles.doneBtnText}>DONE / CLOSE</Text>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 12
  },
  modalCard: {
    backgroundColor: '#0c1322',
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#38bdf8',
    width: '100%',
    maxHeight: '90%',
    padding: 12
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8
  },
  modalTitle: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace'
  },
  modalSub: {
    color: '#64748b',
    fontSize: 8,
    fontWeight: 'bold',
    marginTop: 1
  },
  closeBtn: {
    backgroundColor: '#1e293b',
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#475569'
  },
  closeBtnText: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: 'bold'
  },
  showNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111c2e',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#1e2e45',
    marginBottom: 8
  },
  showLabel: {
    color: '#94a3b8',
    fontSize: 8,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    marginRight: 6
  },
  showInput: {
    flex: 1,
    color: '#facc15',
    fontSize: 10,
    fontWeight: 'bold',
    padding: 0
  },
  actionRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 10
  },
  actionBtn: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1
  },
  actionBtnText: {
    color: '#ffffff',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.5,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace'
  },
  tableHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#162338',
    paddingVertical: 5,
    paddingHorizontal: 6,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderWidth: 1,
    borderColor: '#223652'
  },
  th: {
    color: '#94a3b8',
    fontSize: 7.5,
    fontWeight: '900',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace'
  },
  tableScroll: {
    maxHeight: 280,
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: '#223652',
    backgroundColor: '#0a0f1a'
  },
  emptyText: {
    color: '#64748b',
    fontSize: 9,
    textAlign: 'center',
    paddingVertical: 16
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#16202e'
  },
  chNum: {
    width: 30,
    color: '#38bdf8',
    fontSize: 9,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace'
  },
  roleInput: {
    flex: 1.5,
    color: '#e2e8f0',
    fontSize: 9,
    backgroundColor: '#111827',
    paddingVertical: 2,
    paddingHorizontal: 4,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: '#1f2937',
    marginRight: 4
  },
  typePill: {
    width: 45,
    paddingVertical: 1,
    borderRadius: 2,
    alignItems: 'center',
    marginRight: 4
  },
  typePillDup: {
    backgroundColor: '#1e3a5f'
  },
  typePillSimp: {
    backgroundColor: '#7c2d12'
  },
  typePillText: {
    color: '#f8fafc',
    fontSize: 7,
    fontWeight: '900'
  },
  freqCell: {
    flex: 1.2,
    color: '#facc15',
    fontSize: 8.5,
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: 'bold'
  },
  toneInput: {
    width: 55,
    color: '#34d399',
    fontSize: 8.5,
    textAlign: 'center',
    backgroundColor: '#111827',
    paddingVertical: 2,
    paddingHorizontal: 2,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: '#1f2937',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace'
  },
  doneBtn: {
    backgroundColor: '#1e293b',
    paddingVertical: 8,
    borderRadius: 4,
    alignItems: 'center',
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#475569'
  },
  doneBtnText: {
    color: '#cbd5e1',
    fontSize: 9.5,
    fontWeight: '900',
    letterSpacing: 0.5
  }
});
